source 'https://rubygems.org'

gem 'rspec'
gem 'guard'
gem 'rake'
gem 'hamster'
gem 'guard-rspec'
gem 'thor'
gem 'distribution'
gem 'sinatra'
gem 'haml'
gem 'foreman'
gem 'shotgun'
gem 'addressable'
gem 'jruby_curses', :git => "https://github.com/jeanlazarou/jruby_curses.git" if RUBY_PLATFORM =~ /java/